type SortAndFilter = {
	type: string | null,
	color: string | null,
	top: string | null,
	bottom: string | null,
	pantsType: string | null,
	price: string | null,
	priceLimit: string | null,
	material: string | null,
	useType: string | null,
}

type Item = {
	id: string
	name: string
	color: string
	images: string[]
	sliderImages: string[]
	price: number
	oldPrice: number
}

const temporaryItems: Item[] = [
	{
		id: '1',
		name: 'Printed bikini top',
		color: 'orange',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 25000,
		oldPrice: 26000,
	},
	{
		id: '2',
		name: 'Striped swimsuit',
		color: 'blue',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 28000,
		oldPrice: 30000,
	},
	{
		id: '3',
		name: 'Floral bikini set',
		color: 'pink',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 32000,
		oldPrice: 35000,
	},
	{
		id: '4',
		name: 'Solid one-piece',
		color: 'black',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 22000,
		oldPrice: 24000,
	},
	{
		id: '5',
		name: 'Tie-dye bikini',
		color: 'multicolor',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 27000,
		oldPrice: 29000,
	},
	{
		id: '6',
		name: 'High-waist bikini',
		color: 'red',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 31000,
		oldPrice: 33000,
	},
	{
		id: '7',
		name: 'Sporty swim top',
		color: 'navy',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 24000,
		oldPrice: 26000,
	},
	{
		id: '8',
		name: 'Cheeky bikini bottom',
		color: 'yellow',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 18000,
		oldPrice: 20000,
	},
	{
		id: '9',
		name: 'Crochet cover-up',
		color: 'white',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 35000,
		oldPrice: 38000,
	},
	{
		id: '10',
		name: 'Mesh swim dress',
		color: 'green',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 42000,
		oldPrice: 45000,
	},
	{
		id: '11',
		name: 'Bandeau bikini',
		color: 'purple',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 23000,
		oldPrice: 25000,
	},
	{
		id: '12',
		name: 'Ruffled swimsuit',
		color: 'teal',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 38000,
		oldPrice: 40000,
	},
	{
		id: '13',
		name: 'Cut-out one-piece',
		color: 'burgundy',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 41000,
		oldPrice: 44000,
	},
	{
		id: '14',
		name: 'Tropical print bikini',
		color: 'turquoise',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 29000,
		oldPrice: 32000,
	},
	{
		id: '15',
		name: 'Halter neck swimsuit',
		color: 'coral',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 34000,
		oldPrice: 36000,
	},
	{
		id: '16',
		name: 'Sheer cover-up',
		color: 'beige',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 26000,
		oldPrice: 28000,
	},
	{
		id: '17',
		name: 'Belted swim dress',
		color: 'maroon',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 47000,
		oldPrice: 50000,
	},
	{
		id: '18',
		name: 'Off-shoulder swimsuit',
		color: 'mint',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 39000,
		oldPrice: 42000,
	},
	{
		id: '19',
		name: 'High-neck bikini',
		color: 'lavender',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 31000,
		oldPrice: 34000,
	},
	{
		id: '20',
		name: 'Side-tie bikini',
		color: 'peach',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 27000,
		oldPrice: 29000,
	},
	{
		id: '21',
		name: 'Animal print bikini',
		color: 'leopard',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 33000,
		oldPrice: 36000,
	},
	{
		id: '22',
		name: 'Retro high-waist',
		color: 'polka dot',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 36000,
		oldPrice: 39000,
	},
	{
		id: '23',
		name: 'Sporty one-piece',
		color: 'charcoal',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 29000,
		oldPrice: 32000,
	},
	{
		id: '24',
		name: 'Cropped swim top',
		color: 'sky blue',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 21000,
		oldPrice: 23000,
	},
	{
		id: '25',
		name: 'Wrap swimsuit',
		color: 'emerald',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 44000,
		oldPrice: 47000,
	},
	{
		id: '26',
		name: 'Bikini with rings',
		color: 'gold',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 37000,
		oldPrice: 40000,
	},
	{
		id: '27',
		name: 'Mesh panel swimsuit',
		color: 'rose',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 41000,
		oldPrice: 44000,
	},
	{
		id: '28',
		name: 'Tassel bikini',
		color: 'mustard',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 32000,
		oldPrice: 35000,
	},
	{
		id: '29',
		name: 'Long-sleeve swim top',
		color: 'denim',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 38000,
		oldPrice: 41000,
	},
	{
		id: '30',
		name: 'Cut-out bikini',
		color: 'silver',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 34000,
		oldPrice: 37000,
	},
	{
		id: '31',
		name: 'Ruched one-piece',
		color: 'taupe',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 36000,
		oldPrice: 39000,
	},
	{
		id: '32',
		name: 'Underwire bikini',
		color: 'ruby',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 29000,
		oldPrice: 32000,
	},
	{
		id: '33',
		name: 'Bandeau one-piece',
		color: 'sapphire',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 42000,
		oldPrice: 45000,
	},
	{
		id: '34',
		name: 'Tie-front bikini',
		color: 'magenta',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 31000,
		oldPrice: 34000,
	},
	{
		id: '35',
		name: 'Scalloped swimsuit',
		color: 'pearl',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 45000,
		oldPrice: 48000,
	},
	{
		id: '36',
		name: 'Strappy back bikini',
		color: 'bronze',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 33000,
		oldPrice: 36000,
	},
	{
		id: '37',
		name: 'Shirred swim top',
		color: 'blush',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 28000,
		oldPrice: 31000,
	},
	{
		id: '38',
		name: 'High-cut swimsuit',
		color: 'graphite',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 40000,
		oldPrice: 43000,
	},
	{
		id: '39',
		name: 'Padded bikini',
		color: 'ivory',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 30000,
		oldPrice: 33000,
	},
	{
		id: '40',
		name: 'Cold-shoulder swim',
		color: 'plum',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 37000,
		oldPrice: 40000,
	},
	{
		id: '41',
		name: 'Seamless bikini',
		color: 'mauve',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 32000,
		oldPrice: 35000,
	},
	{
		id: '42',
		name: 'Tankini set',
		color: 'crimson',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 35000,
		oldPrice: 38000,
	},
	{
		id: '43',
		name: 'Boho swim cover',
		color: 'khaki',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 39000,
		oldPrice: 42000,
	},
	{
		id: '44',
		name: 'Racerback swimsuit',
		color: 'indigo',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 31000,
		oldPrice: 34000,
	},
	{
		id: '45',
		name: 'Triangle bikini',
		color: 'fuchsia',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 25000,
		oldPrice: 28000,
	},
	{
		id: '46',
		name: 'Swim shorts set',
		color: 'olive',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 36000,
		oldPrice: 39000,
	},
	{
		id: '47',
		name: 'Metallic swimsuit',
		color: 'copper',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 48000,
		oldPrice: 51000,
	},
	{
		id: '48',
		name: 'Smocked bikini',
		color: 'rose gold',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 34000,
		oldPrice: 37000,
	},
	{
		id: '49',
		name: 'Surplice swimsuit',
		color: 'aqua',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 41000,
		oldPrice: 44000,
	},
	{
		id: '50',
		name: 'Bikini with skirt',
		color: 'lilac',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 37000,
		oldPrice: 40000,
	},
	{
		id: '51',
		name: 'Square neck swim',
		color: 'terracotta',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 39000,
		oldPrice: 42000,
	},
	{
		id: '52',
		name: 'Deep V swimsuit',
		color: 'champagne',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 43000,
		oldPrice: 46000,
	},
	{
		id: '53',
		name: 'Bikini with chains',
		color: 'gunmetal',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 45000,
		oldPrice: 48000,
	},
	{
		id: '54',
		name: 'Wrap bikini top',
		color: 'peacock',
		images: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg', '/item-4.jpg', '/item-5.jpg', '/item-6.jpg'],
		sliderImages: ['/item-1.jpg', '/item-2.jpg', '/item-3.jpg'],
		price: 32000,
		oldPrice: 35000,
	}
];

export const useCatalogStore = defineStore('catalog', () => {
	const desktopStrokeCardCount = ref<string>('4')
	const mobileStrokeCardCount = ref<string>('2')
	const sortAndFilter = ref<SortAndFilter>({
		type: null,
		color: null,
		top: null,
		bottom: null,
		pantsType: null,
		price: null,
		priceLimit: null,
		material: null,
		useType: null,
	})
	const items = ref<Item[]>(temporaryItems)
	
	const reset = () => {
		for (const key in sortAndFilter.value) {
			sortAndFilter.value[key as keyof SortAndFilter] = null
		}
	}
	
	return {
		desktopStrokeCardCount,
		mobileStrokeCardCount,
		sortAndFilter,
		items,
		reset,
	}
})